name: unified-ai-platform
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Python
  - python=3.9

  # Core Data Science
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0

  # Machine Learning
  - scikit-learn>=1.3.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0

  # System Tools
  - pip>=23.0.0

  # PyTorch (from pytorch channel)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cpuonly

  # Pip-only dependencies
  - pip:
    # Gradient Boosting
    - xgboost>=2.0.0
    - lightgbm>=4.0.0
    - catboost>=1.2.0

    # Deep Learning
    - tensorflow>=2.13.0
    - keras>=2.13.0

    # NLP
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - sentencepiece>=0.1.99
    - spacy>=3.6.0
    - nltk>=3.8.0
    - gensim>=4.3.0

    # Time Series
    - prophet>=1.1.4
    - statsmodels>=0.14.0
    - pmdarima>=2.0.3

    # AutoML
    - optuna>=3.3.0
    - hyperopt>=0.2.7

    # Explainability
    - shap>=0.42.0
    - lime>=0.2.0.1
    - interpret>=0.4.0

    # MLOps
    - mlflow>=2.8.0
    - wandb>=0.15.0

    # API & Web
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.23.0
    - pydantic>=2.0.0
    - python-multipart>=0.0.6

    # Dashboard
    - streamlit>=1.28.0
    - streamlit-option-menu>=0.3.6

    # Visualization
    - plotly>=5.17.0
    - altair>=5.0.0

    # Data Handling
    - pyarrow>=13.0.0
    - openpyxl>=3.1.0
    - sqlalchemy>=2.0.0
    - psycopg2-binary>=2.9.0
    - pymongo>=4.5.0

    # Utilities
    - joblib>=1.3.0
    - tqdm>=4.66.0
    - python-dotenv>=1.0.0
    - pyyaml>=6.0.0
    - requests>=2.31.0

    # Data Validation
    - pandera>=0.17.0
    - great-expectations>=0.17.0

    # Model Serving
    - bentoml>=1.1.0

    # Testing
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.0
    - pytest-asyncio>=0.21.0

    # Code Quality
    - black>=23.7.0
    - flake8>=6.1.0
    - isort>=5.12.0
    - mypy>=1.5.0
    - pylint>=2.17.0

    # Documentation
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0

    # Performance
    - numba>=0.57.0
    - dask[complete]>=2023.8.0

    # Feature Engineering
    - feature-engine>=1.6.0
    - category-encoders>=2.6.0
    - imbalanced-learn>=0.11.0

    # Outlier Detection
    - pyod>=1.1.0

    # Image Processing
    - pillow>=10.0.0
    - opencv-python>=4.8.0

    # Dimensionality Reduction
    - umap-learn>=0.5.4

    # Fairness & Bias
    - fairlearn>=0.9.0
    - aif360>=0.5.0

    # Model Compression
    - onnx>=1.14.0
    - onnxruntime>=1.15.0
